name: task_earn
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
flutter_gen:
  output: lib/gen/
  line_length: 80
  # Optional
  integrations:
    flutter_svg: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: AnekDevanagari-Bold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Bold.ttf
  - family: AnekDevanagari-Condensed-Bold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-Bold.ttf
  - family: AnekDevanagari-Condensed-ExtraBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-ExtraBold.ttf
  - family: AnekDevanagari-Condensed-Light
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-Light.ttf
  - family: AnekDevanagari-Condensed-Medium
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-Medium.ttf
  - family: AnekDevanagari-Condensed-Regular
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-Regular.ttf
  - family: AnekDevanagari-Condensed-SemiBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-SemiBold.ttf
  - family: AnekDevanagari-Condensed-Thin
    fonts:
      - asset: assets/fonts/AnekDevanagari-Condensed-Thin.ttf
  - family: AnekDevanagari-Expanded-Bold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-Bold.ttf
  - family: AnekDevanagari-Expanded-ExtraBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-ExtraBold.ttf
  - family: AnekDevanagari-Expanded-Light
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-Light.ttf
  - family: AnekDevanagari-Expanded-Medium
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-Medium.ttf
  - family: AnekDevanagari-Expanded-Regular
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-Regular.ttf
  - family: AnekDevanagari-Expanded-SemiBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-SemiBold.ttf
  - family: AnekDevanagari-Expanded-Thin
    fonts:
      - asset: assets/fonts/AnekDevanagari-Expanded-Thin.ttf
  - family: AnekDevanagari-ExtraBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-ExtraBold.ttf
  - family: AnekDevanagari-ExtraLight
    fonts:
      - asset: assets/fonts/AnekDevanagari-ExtraLight.ttf
  - family: AnekDevanagari-Light
    fonts:
      - asset: assets/fonts/AnekDevanagari-Light.ttf
  - family: AnekDevanagari-Medium
    fonts:
      - asset: assets/fonts/AnekDevanagari-Medium.ttf
  - family: AnekDevanagari-Regular
    fonts:
      - asset: assets/fonts/AnekDevanagari-Regular.ttf
  - family: AnekDevanagari-SemiBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiBold.ttf
  - family: AnekDevanagari-SemiCondensed-Bold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-Bold.ttf
  - family: AnekDevanagari-SemiCondensed-ExtraBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-ExtraBold.ttf
  - family: AnekDevanagari-SemiCondensed-Light
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-Light.ttf
  - family: AnekDevanagari-SemiCondensed-Medium
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-Medium.ttf
  - family: AnekDevanagari-SemiCondensed-Regular
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-Regular.ttf
  - family: AnekDevanagari-SemiCondensed-SemiBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-SemiBold.ttf
  - family: AnekDevanagari-SemiCondensed-Thin
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiCondensed-Thin.ttf
  - family: AnekDevanagari-SemiExpanded-Bold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-Bold.ttf
  - family: AnekDevanagari-SemiExpanded-ExtraBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-ExtraBold.ttf
  - family: AnekDevanagari-SemiExpanded-Light
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-Light.ttf
  - family: AnekDevanagari-SemiExpanded-Medium
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-Medium.ttf
  - family: AnekDevanagari-SemiExpanded-Regular
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-Regular.ttf
  - family: AnekDevanagari-SemiExpanded-SemiBold
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-SemiBold.ttf
  - family: AnekDevanagari-SemiExpanded-Thin
    fonts:
      - asset: assets/fonts/AnekDevanagari-SemiExpanded-Thin.ttf
  - family: AnekDevanagari-Thin
    fonts:
      - asset: assets/fonts/AnekDevanagari-Thin.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
