// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKKqk6YjJOUnGdYWhmm58uZYQEp4qnzLw',
    appId: '1:669580609258:web:6833d6fef1c732d4147993',
    messagingSenderId: '669580609258',
    projectId: 'task-earn-1057a',
    authDomain: 'task-earn-1057a.firebaseapp.com',
    storageBucket: 'task-earn-1057a.appspot.com',
    measurementId: 'G-9M8H1KN6BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3RUPd6q0DTgzFwN-uACqtsRzNWIii4ig',
    appId: '1:669580609258:android:d3638f259d39c246147993',
    messagingSenderId: '669580609258',
    projectId: 'task-earn-1057a',
    storageBucket: 'task-earn-1057a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr0Vu1E-Zf3JcII7N7vzo7JiZldaO7IfE',
    appId: '1:669580609258:ios:0f4728aa21d80064147993',
    messagingSenderId: '669580609258',
    projectId: 'task-earn-1057a',
    storageBucket: 'task-earn-1057a.appspot.com',
    iosBundleId: 'com.example.taskEarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr0Vu1E-Zf3JcII7N7vzo7JiZldaO7IfE',
    appId: '1:669580609258:ios:0f4728aa21d80064147993',
    messagingSenderId: '669580609258',
    projectId: 'task-earn-1057a',
    storageBucket: 'task-earn-1057a.appspot.com',
    iosBundleId: 'com.example.taskEarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKKqk6YjJOUnGdYWhmm58uZYQEp4qnzLw',
    appId: '1:669580609258:web:13c157c456dc3ec9147993',
    messagingSenderId: '669580609258',
    projectId: 'task-earn-1057a',
    authDomain: 'task-earn-1057a.firebaseapp.com',
    storageBucket: 'task-earn-1057a.appspot.com',
    measurementId: 'G-24LNYYXJFD',
  );
}
